#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_CLOCK_CONTROL=y
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_ESB=y

CONFIG_ESB_FAST_SWITCHING=y
CONFIG_ESB_FAST_CHANNEL_SWITCHING=y
CONFIG_ESB_RX_FIFO_SIZE=40
CONFIG_ESB_TX_FIFO_SIZE=40

CONFIG_ESB_PTX_TX_LENGTH=10

# 1kHz packet rate
# CONFIG_ESB_PTX_DELAY=1000
# 2kHz packet rate
# CONFIG_ESB_PTX_DELAY=500
# 4kHz packet rate
# CONFIG_ESB_PTX_DELAY=250
CONFIG_ESB_PTX_DELAY=125
# CONFIG_ESB_PTX_DELAY=100000
CONFIG_SPIN_VALIDATE=n

# Security
CONFIG_NRF_SECURITY=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y

CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=8192
CONFIG_MAIN_STACK_SIZE=4096

# CONFIG_CLOAK=y
CONFIG_JETSTREAM=y
