#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_ESB=y
CONFIG_DK_LIBRARY=y
CONFIG_CLOCK_CONTROL=y

CONFIG_ESB_FAST_SWITCHING=y
CONFIG_ESB_FAST_CHANNEL_SWITCHING=y
CONFIG_ESB_PRX_TX_LENGTH=15

# Security
CONFIG_NRF_SECURITY=y
CONFIG_MBEDTLS_PSA_CRYPTO_C=y

CONFIG_MBEDTLS_ENABLE_HEAP=y
CONFIG_MBEDTLS_HEAP_SIZE=8192
CONFIG_MAIN_STACK_SIZE=4096

# CONFIG_CLOAK=y
CONFIG_JETSTREAM=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_SPIN_VALIDATE=n
# CPU usage
# CONFIG_LOG_BACKEND_UART=y
# #CONFIG_LOG_BACKEND_RTT=y
# CONFIG_THREAD_ANALYZER=y
# #CONFIG_THREAD_ANALYZER_USE_PRINTK=y
# CONFIG_THREAD_ANALYZER_AUTO=y
# CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5
# CONFIG_THREAD_NAME=y
# #CONFIG_LOG_BUFFER_SIZE=12048
# CONFIG_SPEED_OPTIMIZATIONS=y
